import { Plus_Jakarta_Sans } from "next/font/google";
import Header from "./@components/header";
import Footer from "./@components/footer";

// styling
import "./globals.css";

const jakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jakartaSans.className}>
        <Header />

        <main className="relative min-h-screen">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
