import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import { DefaultLayout } from "@/components/layouts";

// styling
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const jakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jakartaSans.className}>

        <DefaultLayout>
          {children}
        </DefaultLayout>

      </body>
    </html>
  );
}
